[package]
name = "ahc-evaluation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
indicatif = "0.17.5"
itertools = "0.11.0"
rayon = "1.7.0"
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.5"
