[thread]
# Number of threads used for evaluation.
# If not specified, it is determined automatically.
thread_num = 8

[path]
# Path of the seed list file.
seed_file = "tools/seeds.txt"

# Path of the directory of input files.
input_dir = "tools/in"

# Path of the directory of output files.
output_dir = "evaluation/out"

# Path of the file that outputs a list summarizing the score and execution time for each seed.
evaluation_record = "evaluation/summary.csv"

[command]
# Build command for submission code.
# Specify an empty array if build execution is not required.
build.submission = ["cargo", "build", "--release"]

# Build command for local tester.
# Specify an empty array if build execution is not required.
build.tester = []

# Execution command for submission code.
execute.submission = ["target/release/submission"]

# Execution command for local tester.
# The following placeholders can be used (Placeholders must be quoted independently).
# - `{input}`: The path of the input file corresponding to the seed.
# - `{output}`: The path of the output file corresponding to the seed.
# - `{cmd}`: Execution command of the submission code.
execute.tester = ["tools/tester", "{input}", "{output}"]

# Set this flag to `true` if the submission code is to be executed via the local tester rather than independently.
execute.integrated = false
